apiVersion: v1
kind: Service
metadata:
  name: tsvai-harness-api
  namespace: tsvai
  labels:
    app: tsvai-harness
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: api
    protocol: TCP
  selector:
    app: tsvai-harness
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: tsvai-harness-loadbalancer
  namespace: tsvai
  labels:
    app: tsvai-harness
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 80
    targetPort: api
    protocol: TCP
  selector:
    app: tsvai-harness
---
apiVersion: v1
kind: Service
metadata:
  name: tsvai-harness-nodeport
  namespace: tsvai
  labels:
    app: tsvai-harness
spec:
  type: NodePort
  ports:
  - name: api
    port: 3000
    targetPort: api
    nodePort: 30000
    protocol: TCP
  selector:
    app: tsvai-harness
